// Auto-generated by scripts/convert-csv-to-places.mjs. Do not edit manually.
import fullPoiIndexJson from "./generatedPoiIndex.json";

export type FullPoiRecord = {
  id: string;
  poiId?: string;
  name: string;
  categoryLabel: string;
  rawCategory?: string;
  subtype?: string;
  address?: string;
  lng: number | null;
  lat: number | null;
  score?: string;
  price?: string;
  openTime?: string;
  phone?: string;
  tags: string[];
  summary?: string;
  imageUrl?: string;
  fallbackImageUrl?: string;
  allImageUrls: string[];
  dynamicText?: string;
  source: string;
  remark?: string;
};

export const fullPoiIndex = fullPoiIndexJson as FullPoiRecord[];
