// Auto-generated by scripts/convert-csv-to-places.mjs. Do not edit manually.

export const datasetMeta = {
  "generatedAt": "2026-07-09T06:43:08.446Z",
  "sourceFiles": {
    "tiered": "src/data/all_tiered_dataset.csv",
    "fullPoi": "src/data/full_poi_dataset.csv"
  },
  "tieredRows": 450,
  "generatedPlaces": 450,
  "skippedInvalidCoordinate": 0,
  "fullPoiRows": 2279,
  "categoryCounts": {
    "景点": 60,
    "美食": 60,
    "酒店": 60,
    "医院": 60,
    "停车场": 70,
    "公安/警务点": 70,
    "卫生间": 70
  },
  "tierCounts": {
    "L4": 40,
    "L3": 170,
    "L2": 240
  },
  "fullPoiCategoryCounts": {
    "景点": 225,
    "美食": 200,
    "酒店": 225,
    "停车场": 225,
    "医院": 200,
    "公交站": 225,
    "卫生间": 411,
    "充电站": 297,
    "公安/警务点": 271
  }
} as const;
